### ISSUE TITLE
Issue: Choice option on verification

### ISSUE THREAD

**Issue by ikcam** [ramarketing/gbm-renamer#2]
The default option changed after the business gets renamed.

<img width="1312" alt="captura de pantalla 2019-02-12 a la s 09 36 24" src="https://user-images.githubusercontent.com/1041823/52642810-b7d43800-2ea9-11e9-9ff2-e96831c31c4d.png">

- Name: `Bright Attic Cleaning Masters`
- Email: `trottercranstounmajor@gmail.com`
- Password: `AdPoXU7Aym`
- Recovery email: `orrenh4zvg21@hotmail.com`
- Final name: `Purple Construction`
- Final category: `General Contractor`
- Final description: `The best home remodeling company`
- Final website: `http://purpleconstructionca.com`

Both methods should work:
- When the option is a company name (like this)
- When the option is the phone number

**Comment by aleoreina** [comment]
Se creara una rama llamada VerifyDoesntMatch para comitear y guarda los cambios solo a la espera de prueba. Estos cambios provendran de la rama dev. Al final, Juntaremos y eliminaremos las ramas que sean necesarias de eliminar.

**Comment by aleoreina** [comment]
Already done. 
3 days ago
