### ISSUE TITLE
Issue: Not detecting when the password is wrong

### ISSUE THREAD

**Issue by ikcam** [ramarketing/gbm-renamer#3]
![captura de pantalla 2019-02-15 a la s 19 00 25](https://user-images.githubusercontent.com/1041823/52890682-0e649f00-3154-11e9-97c2-1d6e0ad01e77.png)

1. The robot must be able to detect when the password it's wrong.
2. Run `credential.report_fail()`

**Comment by ikcam** [comment]
Looks like this issue also crashes the Terminal/MS-DOS console, probably it's a memory abuse issue.

**Comment by aleoreina** [comment]
Problem was coming from message.py
Already fixed for english.
Observation: Pending for final version add a translate function.
Already done. 

Branch: VerifyDoesnMatch
